# Generated by Django 4.1.9 on 2023-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('appd_application_name', models.CharField(max_length=100)),
                ('timestamp', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'appd_events_audit',
            },
        ),
    ]
